<?php

namespace App\Http\Requests\Auth;

use App\Http\Requests\BaseRequest;
use Illuminate\Foundation\Http\FormRequest;

class ReigsterRequest extends BaseRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|max:6',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:3|max:10|confirmed'
        ];
    }

    public function messages()
    {
        return [
            'name.required' => '名字不能为空啊',
            'name.max' => '名字太长了,最长 6',
            'email.unique' => '邮箱存在了',
        ];

        // TODO: Change the autogenerated stub
    }
}
